### ISSUE TITLE
client login yields error

### ISSUE THREAD

**Issue by cpg** [samsymons/RedditKit.rb#46]
I tried:

`@client = RedditKit::Client.new 'MyAccount', 'xyz'`

and I get this. Using ruby 2.3.0. Ideas?

```
/Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/utilities.rb:71:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/utilities.rb:71:in `object_kind_from_response'
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/utilities.rb:41:in `object_class_from_response'
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/utilities.rb:78:in `object_from_response'
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/users.rb:17:in `user'
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client/account.rb:22:in `sign_in'
	from /Users/cpg/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/redditkit-1.0.2/lib/redditkit/client.rb:61:in `initialize'
 ....
```

**Comment by shotop** [comment]
+1 - seeing the same issue
